pesto-students/batch-7-trailblazers

- package.json
- yarn.lock
issue #3 
Added missing package for ESLint to extends standard from.
resolves #3
> Add package: Airbnb standards

- .eslintrc.json
- client/package.json
- client/src/App.test.js
- client/src/setupTests.js
- client/yarn.lock
- server/app.js
- server/app.test.js
- server/config/config.js
- server/config/index.js
- server/package.json
- server/yarn.lock
**Enzyme** for _React_.
**Jest** for _JavaScript_ files of the server.
**Test** for FrontEnd(client folder) & 
BackEnd(server folder) side :-
Resolves #17
> Setup Enzyme & Jest (issue #17)

- .travis.yml
- package.json
Resolved #2 (Setup circle-ci/travis for CI)
Added .travis.yml file
> Setup circle-ci/travis for CI

- .travis.yml
- Procfile
- package.json
Resolved #13 
Added Procfile to configure the Heroku deployment
Update .travis.yml file to configure the deployment of Netlify and Heroku after CI
> Complete Setup CD on netlify and heroku

- .travis.yml
- package.json
- server/app.js
- server/package.json
- server/yarn.lock
- yarn.lock
> Fixed Bug Travis connection with Mongodb

- server/package.json
> Fix: update server package.json and add serve script to run on heroku

- .travis.yml
- server/package.json
update index.js to app.js
Resolved #45
> Fix: Server package.json script 'serve'

- server/.babelrc
- server/app.js
- server/app.test.js
- server/config/database.js
- server/config/index.js
- server/controllers/authentication.js
- server/models/userModel.js
- server/package.json
- server/routes/index.js
- server/test/signup.test.js
- server/utils/helpers.js
- server/yarn.lock
* Configured database 
* Created user schema
* Created /signup API
> Sign up API

- client/src/components/Header/Header.js
- client/src/components/Header/Header.stories.js
- client/src/components/Header/Header.test.js
> Header component

- server/app.js
- server/config/constants.js
- server/controllers/authentication.js
- server/controllers/dashboardController.js
- server/models/autoIncrementModel.js
- server/models/boardModel.js
- server/models/dashboardModel.js
- server/routes/dashboard.js
- server/test/dashboard.test.js
- server/test/signup.test.js
Resolved #31 
Added test case for add board
Create API to save board
Create Dashboard and Board Schema 
Create Autoincremented Model to get unique autoincremented id
> feat: Add board API in server

- server/app.js
- server/config/index.js
- server/config/passport.js
- server/controllers/authentication.js
- server/middlewares/authenticateRoute.js
- server/models/userModel.js
- server/package.json
- server/routes/dashboard.js
- server/routes/index.js
- server/test/login.test.js
- server/test/signup.test.js
- server/utils/constants.js
- server/utils/helpers.js
- server/yarn.lock
> feat: add login api with passport config

- client/src/App.css
- client/src/App.js
- client/src/components/Board/Settings/MembersList.js
- client/src/components/Board/Settings/settings.css
- client/src/components/SignUp/SignUp.test.js
- client/src/constants.js
- client/yarn.lock
- server/config/constants.js
- server/controllers/boardSettingsController.js
> feat: Create UI for board members and integrate API

- client/src/App.css
- client/src/App.js
- client/src/components/AppMenu/AppMenu.css
- client/src/components/AppMenu/AppMenu.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Board/Settings/MembersList.js
- client/src/components/Button/Button.js
- client/src/components/Button/Button.test.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Header/Header.js
- server/config/constants.js
- server/controllers/boardSettingsController.js
- server/controllers/dashboardController.js
- server/models/boardModel.js
- server/utils/constants.js
Resolved #81 #82 
Create component for Board details
Create a component for the page title
Create route for members list
> fix: Added board component & fix bugs related to dashboard API integration

- server/controllers/boardController.js
- server/models/boardModel.js
> fix: Get issue API

- client/package.json
- client/src/components/Board/BoardDetails.js
- client/src/components/Dashboard/AddBoardForm.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Header/index.js
- client/src/components/Issue/Issue.css
- client/src/components/Issue/Issue.js
- client/src/components/Issue/index.js
- client/src/components/KanbanView/KanbanView.css
- client/src/components/KanbanView/KanbanView.js
- client/src/components/KanbanView/index.js
- client/src/components/LifeCycleColumn/LifeCycleColumn.css
- client/src/components/LifeCycleColumn/LifeCycleColumn.js
- client/src/components/LifeCycleColumn/index.js
- client/src/components/SnackBar/SnackBarContentWrapper.js
- client/yarn.lock
- server/controllers/boardController.js
- server/controllers/dashboardController.js
- server/models/boardModel.js
- server/test/board.test.js
- server/test/boardSettings.test.js
- server/test/dashboard.test.js
> feat: add kanban component

- server/app.js
- server/controllers/boardController.js
- server/controllers/boardSettingsController.js
- server/models/commentModel.js
- server/models/issueModel.js
- server/routes/board.js
- server/routes/boardSettings.js
- server/test/boardSettings.test.js
- server/utils/constants.js
Resolved #69 
Create API to add issue
> feat: Create API to add issue and add test case

- README.md
**type:** doc
Added project tasks to keep track of completed work on the `master` branch.
> doc: add project tasks to README file

- client/src/components/KanbanView/KanbanView.js
- client/src/views/Login/Login.js
- server/app.js
- server/controllers/authentication.js
- server/controllers/boardSettingsController.js
- server/controllers/dashboardController.js
- server/controllers/issueController.js
- server/models/issueModel.js
- server/routes/index.js
- server/routes/issue.js
- server/test/dashboard.test.js
- server/utils/constants.js
- server/utils/helpers.js
> feat: add API to change life-cycle of issue

- client/src/components/Dashboard/Dashboard.js
- client/src/views/Login/Login.js
- server/app.js
- server/controllers/dashboardController.js
Resolved #97 
Tested on Netlify and heroku
> fix: cors issue

- client/src/App.js
- client/src/components/Board/AddIssueModal.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Board/board.css
- client/src/components/CommonComponents/Modal.js
- client/src/components/Dashboard/Dashboard.js
- server/controllers/boardController.js
- server/controllers/dashboardController.js
feat: Integrate add issue API
Resolved #70
> feat: added modal to add issue

- server/config/index.js
- server/controllers/boardController.js
- server/middlewares/authenticateRoute.js
- server/package.json
- server/routes/board.js
- server/utils/constants.js
- server/utils/emailService.js
- server/yarn.lock
> Inviting a new User via email

- client/src/components/Board/BoardDetails.js
> Invite Email Button on UI

- README.md
> doc: fix rendering of checkbox for project tasks

- client/src/App.css
- client/src/App.js
- client/src/App.test.js
- client/src/components/AppMenu/AppMenu.css
- client/src/components/Board/AddIssueModal.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Board/Settings/MembersList.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/KanbanView/KanbanView.js
- client/src/components/PrivateRoute/PrivateRoute.js
- client/src/index.js
- client/src/views/Login/Login.js
- server/app.js
Solve bugs, Handle network error, fix UI of Add issue button
Resolved #103
> fix: Solve bugs related to ui and functionality

- client/src/App.css
- client/src/App.js
- client/src/components/Board/AddIssueModal.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Button/Button.js
- client/src/components/CommonComponents/Modal.css
- client/src/components/CommonComponents/Modal.js
- client/src/components/Dashboard/AddBoardForm.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/KanbanView/KanbanView.js
- client/src/constants.js
- client/src/theme/index.js
- client/src/theme/theme.js
Fix: Bugs related Modal and changed Modal UI, 
Fix issue of refreshing the kanban view after adding the issue
Add Board Screenshot
> feat: Update Modal design, update fields, added theme

- client/src/App.css
- client/src/components/Board/AddIssueModal.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Button/Button.js
- client/src/components/Dashboard/AddBoardForm.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/DatePicker/DatePicker.js
- client/src/components/IssueDetails/IssueDetails.js
- server/controllers/boardController.js
- server/controllers/issueController.js
- server/models/autoIncrementModel.js
- server/models/issueModel.js
- server/routes/board.js
> fix: solve add id issues and update datepicker

- server/config/passport.js
- server/controllers/authentication.js
- server/routes/index.js
> fix:Login Error message

- client/src/components/IssueDetails/IssueDetails.css
- client/src/components/IssueDetails/IssueDetails.js
- client/src/components/KanbanView/KanbanView.js
- client/src/theme/theme.js
- server/controllers/issueController.js
- server/utils/constants.js
**type:** config
**PR containers**
Integration of update issue API & Issue details component.
> config: integrate api & component of update issue details

- server/controllers/authentication.js
- server/controllers/boardController.js
- server/controllers/invitationEmail.html
- server/controllers/welcomeEmail.html
- server/package.json
> Edd Email Template

- client/src/App.js
- client/src/components/Board/AddIssueModal.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Board/Settings/MembersList.js
- client/src/components/Dashboard/Board.js
- client/src/components/Dashboard/Dashboard.js
- client/src/components/Issue/Issue.js
- client/src/components/IssueDetails/IssueDetails.css
- client/src/components/IssueDetails/IssueDetails.js
- client/src/components/KanbanView/KanbanView.js
- client/src/components/SignUp/SignUp.test.js
- client/src/components/SignUp/__snapshots__/SignUp.test.js.snap
- client/src/theme/theme.js
> bug & refactor: fix ui bugs

- client/src/components/Board/AddIssueModal.js
- client/src/components/Board/BoardDetails.js
- client/src/components/Board/Settings/MembersList.js
- client/src/components/Board/board.css
- client/src/components/CommonComponents/Modal.js
- client/src/components/HeaderWithUserAvatar/HeaderWithUserAvatar.js
- client/src/components/IssueDetails/IssueDetails.css
- client/src/components/IssueDetails/IssueDetails.js
> bug: fix style of Date picker in Issue details

- README.md
- client/src/components/Board/BoardDetails.js
- client/src/components/Header/Header.js
added deployed project link in readme
> fix: Clear email when popup opens & added link to Groot logo 
